services:
    postgresdb:
        image: postgres:latest
        container_name: postgresdb
        ports:
        - "5432:5432"
        environment:
          POSTGRES_DB: Adform 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        volumes:
          - ./Sql Scripts/01_Database_Tables.sql:/docker-entrypoint-initdb.d/01_Database_Tables.sql:ro
          - ./Sql Scripts/02_Generate_Data_Functions.sql:/docker-entrypoint-initdb.d/02_Generate_Data_Functions.sql:ro
          - ./Sql Scripts/03_Generate_Data_Queries.sql:/docker-entrypoint-initdb.d/03_Generate_Data_Queries.sql:ro
          - ./Sql Scripts/04_Order_Details_View.sql:/docker-entrypoint-initdb.d/04_Order_Details_View.sql:ro
          - ./Sql Scripts/05_Get_Data_Functions.sql:/docker-entrypoint-initdb.d/05_Get_Data_Functions.sql:ro
    webapi:
      build:
        context: ./Adform SQL Task
        dockerfile: Dockerfile
      container_name: webapi
      ports:
        - "8080:8080"
      depends_on:
        - postgresdb
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
    cloudbeaver:
        image: dbeaver/cloudbeaver:latest
        container_name: cloudbeaver
        ports:
            - "8978:8978"
        depends_on:
            - postgresdb
        restart: unless-stopped