services:
    postgresdb:
        image: postgres:latest
        container_name: postgresdb
        ports:
        - "5432:5432"
        environment:
          POSTGRES_DB: AdFormSQL 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        volumes:
          - ./01_Database_Tables.sql:/docker-entrypoint-initdb.d/01_Database_Tables.sql:ro
          - ./02_Insert_Customers.sql:/docker-entrypoint-initdb.d/02_Insert_Customers.sql:ro
          - ./03_Insert_Products.sql:/docker-entrypoint-initdb.d/03_Insert_Products.sql:ro
          - ./04_Insert_Orders.sql:/docker-entrypoint-initdb.d/04_Insert_Orders.sql:ro
          - ./05_Insert_OrderLines.sql:/docker-entrypoint-initdb.d/05_Insert_OrderLines.sql:ro
          - ./06_Order_Detail_View.sql:/docker-entrypoint-initdb.d/06_Order_Detail_View.sql:ro
          - ./07_Functions.sql:/docker-entrypoint-initdb.d/07_Functions.sql:ro
          